# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae21a59b3ad40ffd05f6a62e52c8da03518645f618c91764ee714f6e8911b37905957021851548ef5e9b21dbcf19de7de61b2cea9e3574d6ee8d0c05e6fbbc0

test:
  secret_key_base: ed99835666aaa6cdbc67ffd975103f8f6cd40a8c97fbb332bbdac3dce1ab207b20a446277196fce48b9ba83fa8c2544f464dce60dad89b73afbad1bc056589ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
